# Generated by Django 4.2.6 on 2024-08-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dniprocesos',
            old_name='idoperario',
            new_name='id_operario',
        ),
        migrations.RenameField(
            model_name='dniprocesos',
            old_name='idseccion',
            new_name='id_seccion',
        ),
        migrations.RenameField(
            model_name='procesos',
            old_name='categoría',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='procesos',
            old_name='fechahora',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='procesos',
            old_name='idoperario',
            new_name='id_operario',
        ),
        migrations.RenameField(
            model_name='procesos',
            old_name='idordenproduccion',
            new_name='id_ordenproduccion',
        ),
        migrations.RenameField(
            model_name='procesos',
            old_name='idseccion',
            new_name='id_seccion',
        ),
    ]
